import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

import {
  Header,
  ContentContainer,
  Title,
  Subtitle,
  Price,
  Description,
  Main,
  SectionTitle,
  SectionText,
  WatchSection,
  WatchSectionLeft
} from '../styles/home.styles'

import { HomeHeader } from '../components/HomeHeader'
import { Button } from '../components/Button'
import { MoviesSection } from '../components/MoviesSection'
import { DevicesSection } from '../components/DevicesSection'
import { Footer } from '../components/Footer'

import logoImg from '../../public/images/logo.svg'
import homeImg from '../../public/images/home.png'

export default function Landing() {
  return (
    <>
      <Head>
        <title>Disney+</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeHeader />

      <Header>
        <ContentContainer>
          <Image src={logoImg} alt="Disney+" width={160} height={87} />

          <Title>
            Special offer
            <br />
            valid until July 7th
          </Title>
          <Subtitle>The best stories for only</Subtitle>

          <Price>
            R$ 1,90 <span>for the first month</span>
          </Price>

          <Link href="/register" passHref>
            <Button>Sign up now</Button>
          </Link>

          <Description>
            Promotional price of R$1,90 only for the first month, to new
            subscriptions made at Disneyplus.com. From the second month on, the
            monthly price charged will be R$27.90. Valid offer only for
            subscriptions made between July 1st until 7th of 2021. You can
            cancel at any time, without refund, and the subscription will remain
            active until the end of the billing period
          </Description>
        </ContentContainer>
      </Header>

      <Main>
        <WatchSection>
          <WatchSectionLeft>
            <SectionTitle>Watch the way you want</SectionTitle>

            <SectionText>
              Enjoy the big screen experience on your TV, or watch on your
              tablet, laptop, phone and more. You can watch an ever-growing
              selection of titles in 4K. Plus, you can stream on 4 screens at
              once, so everyone’s happy.
            </SectionText>
          </WatchSectionLeft>

          <Image src={homeImg} alt="Watch the way you want" />
        </WatchSection>

        <MoviesSection
          title="Exclusive Disney+ Originals"
          text="Watch never-before-seen movies, series, shorts and more from the world’s greatest storytellers – only available on Disney+"
        />

        <MoviesSection
          title="Endless entertainment"
          text="Discover the best stories from Disney, Pixar, Marvel, Star Wars and National Geographic in one place. From hit movies to timeless classics and new originals – there's something for everyone."
        />

        <DevicesSection title="Available on your favorite devices" />
      </Main>

      <Footer />
    </>
  )
}
